###############################################################################################
#                                      Application                                            #
###############################################################################################
spring:
  application:
    name: Spock with Spring Boot configuraton sample
